### ISSUE TITLE
[BUG] Video restarts automatically

### ISSUE THREAD

**Issue by arellak** [NullDev/YT-Anti-Anti-Adblock#7]
**Describe the bug**
When a video is finished, no end card is shown. It automatically restarts the video.

**To Reproduce**
Go to the end of a video.

**Expected behavior**
I want to see the end card.

**Screenshots**

https://github.com/NullDev/YT-Anti-Anti-Adblock/assets/27505801/cc595760-c895-4d77-8518-c9527f75c27c

**Additional info**
 - OS: Windows 11
 - Browser & Version: Google Chrome 118.0.5993.118
 - AdBlockers & Other Extensions: uBlock Origin

**Additional context**
-

**Comment by NullDev** [comment]
Same bug that cases https://github.com/NullDev/YT-Anti-Anti-Adblock/issues/6
