### ISSUE TITLE
[BUG] Theatre Mode not working, also whole task bar different

### ISSUE THREAD

**Issue by Mr-Chris-VRTY** [NullDev/YT-Anti-Anti-Adblock#9]
**Describe the bug**
Theatre mode is not avaible in any video. Also the hotkey "t" not.
Also the whole task bar is different and some functions are not avaible.

![image](https://github.com/NullDev/YT-Anti-Anti-Adblock/assets/70213538/abe5e78e-4d49-423a-8d30-8d915da18019)
With script

![image](https://github.com/NullDev/YT-Anti-Anti-Adblock/assets/70213538/0ec8f805-3221-45d5-992e-eaaaf17872dc)
Without script

**To Reproduce**
1. Go to YouTube
2. Run any video
3. Try to go in theatre mode
4. See the bug

**Expected behavior**

**Screenshots**

**Additional info**
 - OS: Win 10
 - Browser & Version Google Chrome 119.0.6045.124
 - AdBlockers & Other Extensions: AdBlock Plus, uBlock Origin, uBlock, 

**Additional context**
-

**Comment by NullDev** [comment]
Thank you for the report! I'm currently working on a fix to add the "play next" button and the theatre mode button. Unfortunately the pop-out mode / mini window is currently not possible because the workaround in my userscript uses youtubes iframe API.

**Comment by NullDev** [comment]
I added experimental theater mode in https://github.com/NullDev/YT-Anti-Anti-Adblock/commit/25501af7ecc32b21a8161a3edfcd9f23339328cc as well as the next button and the popout mode button. 
Theater mode is still experimental, please let me know if you encounter any bugs.
